dist: xenial
language: python
cache: pip
sudo: false
install:
  - pip install tox
script: tox
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.5
      env: TOXENV=flake8
